### ISSUE TITLE
Make ESP8266 based heating thermostat

### ISSUE THREAD

**Issue by lukasznowarkiewicz** [lukasznowarkiewicz/smarthome#11]
Subject of this task is to make thermostat based on ESP8266 module:

- [ ] buy required items
- [ ] make hardware part of the device
- [ ] install ESPhome on Gosund SP111
- [ ] add device to the home assistant
- [ ] make thermostat using BetterThermostat (related issue: https://github.com/lukasznowarkiewicz/smarthome/issues/9 - need to make indoor temperature sensor)

**Comment by lukasznowarkiewicz** [comment]
Bought:
-  https://allegro.pl/moje-allegro/zakupy/kupione/a9f2d311-e3d2-3e86-93d7-61d856bd1858
- https://allegro.pl/moje-allegro/zakupy/kupione/987441d3-f312-319d-880a-9700c8b9b951

**Comment by lukasznowarkiewicz** [comment]
Useful links: https://www.youtube.com/watch?v=M_tVWnA0goE

**Comment by lukasznowarkiewicz** [comment]
Useful for Godsund SP111 modification:
https://tom.stevens.se/gosund-sp111-esphome/
https://robinclarke.net/archives/stop-coil-whining-on-gosund-sp111
https://pielatowski.pl/gosund-sp111-tasmota/

**Comment by lukasznowarkiewicz** [comment]
Interesting threat taking into consideration safety of gosund SP111:https://github.com/arendst/Tasmota/issues/5174

**Comment by lukasznowarkiewicz** [comment]
Soldered wires to the pads and connected signals to the USB-UART CP2102  programmer:
![IMG_6501](https://github.com/lukasznowarkiewicz/sm
![IMG_6500](https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/f5cf019e-98ba-49fb-a229-f2610c47eede)
arthome/assets/82212257/d0189a82-2f6a-47ca-a625-cc6af4ec6fa1)

**Comment by lukasznowarkiewicz** [comment]
Used brew packet manager to obtain `lsusb`. Used `lsusb` for finding usb programmer. 
<img width="868" alt="Screenshot 2023-11-27 at 20 06 00" src="https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/d140fe13-be6d-4912-a23f-ccde50a051a6">

**Comment by lukasznowarkiewicz** [comment]
Used picocom for connecting to the device and checking if any debug informations could be read (baud rate determined try and fail method):
<img width="864" alt="Screenshot 2023-11-27 at 20 13 47" src="https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/c333241c-0229-4bc3-aa76-599bca4f4871">
It seems that all connections work.

**Comment by lukasznowarkiewicz** [comment]
Haven't found any tutorial regarding installing ESPHome on Gesund SP111 (about procedure). Based on information that in consists on ordinary ESP8266 tried to just install software using web serial. First attempt failed as boot signal should be pulled to GND while connecting to power in order to enter programming mode. Achieved by touching this pin to the USB casing:
![IMG_6502](https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/b2000313-694b-4a7d-bc8b-1c3d7c9396d3)

<img width="1624" alt="Screenshot 2023-11-27 at 20 15 07" src="https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/e2d56b57-70ea-4626-8e3c-3663fdd99dd1">
<img width="1624" alt="Screenshot 2023-11-27 at 20 15 27" src="https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/fef1d7cf-e5c9-4a3f-ad45-6df6068e440d">
<img width="1624" alt="Screenshot 2023-11-27 at 20 15 35" src="https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/28d49ffa-a656-4460-a772-3c3a3f43287b">
<img width="1624" alt="Screenshot 2023-11-27 at 20 20 23" src="https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/b01b8921-27b5-4893-819f-8379e7ac595e">
Installation succesfull

**Comment by lukasznowarkiewicz** [comment]
Then used config from https://devices.esphome.io/devices/Gosund-SP111
```
substitutions:
  devicename: "gosund_sp111"
  upper_devicename: "Gosund SP111"
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

esphome:
  name: $devicename
  platform: ESP8266
  board: esp8285

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

# Enable over the air updates
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on

# see: https://esphome.io/components/time.html
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server
web_server:
  port: 80

text_sensor:
  - platform: version
    name: "${devicename} - Version"
    icon: mdi:cube-outline

binary_sensor:
  - platform: status
    name: "${devicename} - Status"
    device_class: connectivity

  # toggle relay on/off
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: "${devicename}_button_state"
    on_press:
      - switch.toggle: button_switch

sensor:
  - platform: wifi_signal
    name: "${devicename} - Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    name: "${devicename} - Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

  - platform: total_daily_energy
    name: "${devicename} - Todays Usage"
    power_id: "power_wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:calendar-clock

  - platform: adc
    pin: VCC
    name: "${devicename} - VCC Volt"
    icon: mdi:flash-outline

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 3s

    current:
      name: "${devicename} - Ampere"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:current-ac

    voltage:
      name: "${devicename} - Volt"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline

    power:
      name: "${devicename} - Watt"
      unit_of_measurement: W
      id: "power_wattage"
      icon: mdi:gauge

status_led:
  pin:
    number: GPIO02
    inverted: True
  id: led_blue

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led_red

switch:
  - platform: template
    name: "${devicename} - Switch"
    icon: mdi:power
    optimistic: true
    id: button_switch
    turn_on_action:
      - switch.turn_on: relay
      - output.turn_on: led_red
    turn_off_action:
      - switch.turn_off: relay
      - output.turn_off: led_red
  - platform: gpio
    pin: GPIO15
    id: relay
```
Updated using OTA
<img width="1624" alt="Screenshot 2023-11-27 at 20 25 11" src="https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/c032e495-ed96-4661-b7d0-c7ab4db45c9f">
<img width="1624" alt="Screenshot 2023-11-27 at 20 52 39" src="https://github.com/lukasznowarkiewicz/smarthome/assets/82212257/98a40efa-080a-4f81-84ba-ecaa3d2c61f5">
